spring.application.name=concurrent-lru-cache
cache.capacity=5
spring.datasource.url=jdbc:postgresql://localhost:5432/cachedb
spring.datasource.username=cacheuser
spring.datasource.password=cachepass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
